#!/usr/bin/env bash

open_cmd="$(which xdg-open)"
if [ "$(uname -s)" = "Darwin" ]; then
	open_cmd="$(which open)"
fi

set -e

for repo in "$@"
do
  if [ -e "/tmp/$repo" ]; then
    rm -rf "/tmp/$repo"
  fi
  git clone git@git.fminus.co:CompostInTraining/$repo /tmp/$repo

  cd /tmp/$repo

  for branch in $(git branch --all | grep '^\s*remotes' | egrep --invert-match '(:?HEAD|master)$'); do
    git branch --track "${branch##*/}" "$branch"
  done

  git remote add github git@github.com:CompostInTraining/$repo

  set +e
  gh repo create CompostInTraining/$repo --public --disable-wiki
  set -e


  git push github --all
  git push github --tags

  $open_cmd "https://github.com/CompostInTraining/$repo/settings"
done

