#!/usr/bin/env bash

set -e

for repo in "$@"
do
  git clone git@git.sr.ht:~prplecake/$repo /tmp/$repo

  cd /tmp/$repo

  for branch in $(git branch --all | grep '^\s*remotes' | egrep --invert-match '(:?HEAD|master)$'); do
	  git branch --track "${branch##*/}" "$branch"
  done

  git remote add github git@github.com:prplecake/$repo

  gh repo create $repo --public --disable-wiki


  git push github --all
  git push github --tags

  #xdg-open "https://git.sr.ht/~prplecake/$repo/settings/info"
done

