#!/usr/bin/env bash

open_cmd="$(which xdg-open)"
if [ "$(uname -s)" = "Darwin" ]; then
  open_cmd="$(which open)"
fi

set -e

for repo in "$@"
do
  if [ -e "/tmp/$repo" ]; then
    rm -rf "/tmp/$repo"
  fi
  git clone git@git.sr.ht:~prplecake/$repo /tmp/$repo

  cd /tmp/$repo

  for branch in $(git branch --all | grep '^\s*remotes' | egrep --invert-match '(:?HEAD|master)$'); do
	  git branch --track "${branch##*/}" "$branch"
  done

  git remote add fminus git@git.fminus.co:prplecake/$repo

  git push fminus --all
  git push fminus --tags

  $open_cmd "https://git.fminus.co/prplecake/$repo/settings"
done

