#!/usr/bin/env bash

source scripts/_helpers

TEMP=$(pwd)/.temp
mkdir $TEMP

info "running apt update and apt dist-upgrade"
# sudo apt update && sudo apt dist-upgrade

install_pip () {
    local pyver=$1

    info "installing pip for python $pyver"
    if [ ! -f "$TEMP/get-pip.py" ]; then
        info "no pip"
        # curl https://bootstrap.pypa.io/get-pip.py -o $TEMP/get-pip.py
    else
        info "pip!"
    fi
}

info "checking for python 2"
install_pip 2
install_pip 3

# if python 2 is installed, install pip for it...


# do the same for python 3

# cleanup
rm -rf $TEMP
